### ISSUE TITLE
Allow site to work offline as a PWA

### ISSUE THREAD

**Issue by kimadactyl** [GenderedIntelligence/the-trans-dimension#17]
## User story

As a community development worker with patchy internet and who uses the tube, I need to be able to access TTD without relying on internet so that I can do my work even in adverse circumstances.

## Acceptance criteria

- [ ] TransDim works without internet access
- [ ] If user is online, TransDim data updates at least every 10 mins
- [ ] I can add The Trans Dimesion to my device homescreen

## Implementation notes & questions

- This should work 'out of the box' but will need some config and testing.
- Once we have data sources we'll want to use the pattern of loading initially with static content (generated on release / build) and if there is a connection, do a look-up so people onlibe will always get latest data loading in.
- As a stretch we might want to automate a periodic build so that static content is never more than X days/hours out of date

## Implementation plan

**Comment by katjam** [comment]
Some thinking on this for release 1.0 related to #287

**Comment by kimadactyl** [comment]
I don't think we need this for v1.0 but we do need it to load live data if available. Not sure if this is the same thing or not.
