### ISSUE TITLE
Meta update - remove all refs to 'elm-pages' & add logo + image

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#203]
## Acceptance

- [x] No occurances of 'elm-pages' 
- [x] No occurances of TODO
- [x] Image and or logo in meta info
