### ISSUE TITLE
Meta info strategy

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#49]
## Description

Decide how we want to generate the meta info for each page type.
Look at the markup we are generating and make sure it's what we want for SEO.

## Plan

- [x] Sweep for `elm-pages` in our Page's that may have snuck in from boilerplate done in #154
- [x] Review copy in `Copy.Text` done in #154
- [ ] Add images to each `Page` (all pages use same logo) https://github.com/GenderedIntelligence/the-trans-dimension/issues/244
- [x] Make a Head.Seo generator that the pages can share
