### ISSUE TITLE
Create issue & pull request templates, milestones, labels and how to use docs

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#5]
## Acceptance

- [x]  when I create an issue there is a choice of template
- [x] when I create a pull request there is a template
- [x] there are milestones and labels with clear descriptions of how we use them

## Plan

- [x] Create templates
- [x] Create milestones
- [x] add some readme
- [x] Create labels

## Qusestions

- Do we want to link out to the trello or keep any tasks in sync from there? Ignoring trello for now. Don't need to keep in sync with ganular dev work.
