### ISSUE TITLE
Feature scoping

### ISSUE THREAD

**Issue by katjam** [GenderedIntelligence/the-trans-dimension#82]
## Plan

- Look through [fFf]
- Generate Issues & effort value them --> prioritise into a milestone
- Remove placeholders from wireframe (before testing?)

## Generate issues

- [x] #79
- [x] Partner Page: Source partner contact info (is a field in allPartners)
- [ ] Partner Page: Map (Mapbox - https://docs.mapbox.com) #195
- [x] #61
- [x] Event Page: Source event url (Event description is markdown)
- [ ] Event Page: Map #195
- [x] #169
- [x] #197
- [x] #193
- [ ] #192
- [x] #188
- [x] #98

## Backlog or never

- [ ] Partners Page: Map
- [ ] Partners Page: Filter partners
